# Generated by Django 5.0 on 2023-12-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_weather', '0003_messagesusermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesusermodel',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
