# Generated by Django 5.0 on 2023-12-23 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_weather', '0004_messagesusermodel_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagesusermodel',
            old_name='autor_message',
            new_name='author_message',
        ),
        migrations.DeleteModel(
            name='SiteUserModel',
        ),
    ]
